import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import NavBar from "@/components/ui/Navbar/Navbar";
import { usePathname } from "next/navigation";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#DCF3FF]`}>
        <div className="parent">
          <NavBar />
          <div className="children">{children}</div>
        </div>
      </body>
    </html>
  );
}
